"""Property-based tests for the LanguageTool utility functions."""

from hypothesis import given, settings
from hypothesis import strategies as st

import language_tool_python


@given(text=st.text())
@settings(max_examples=500)
def test_prop_correct_with_empty_matches_is_identity(text: str) -> None:
    """correct(text, []) must always return the original text unchanged.

    This verifies the fundamental contract that applying zero corrections
    is a no-op, regardless of the text content (empty, unicode, emojis...).

    :param text: Arbitrary string generated by Hypothesis.
    :raises AssertionError: If the corrected text differs from the input.
    """
    assert language_tool_python.utils.correct(text, []) == text
