"""Property-based tests for the LanguageTool utility functions."""

from __future__ import annotations

from hypothesis import given, settings
from hypothesis import strategies as st

import language_tool_python
from language_tool_python.utils import TextStatus, classify_matches


@given(text=st.text())
@settings(max_examples=500)
def test_prop_correct_with_empty_matches_is_identity(text: str) -> None:
    """correct(text, []) must always return the original text unchanged.

    This verifies the fundamental contract that applying zero corrections
    is a no-op, regardless of the text content (empty, unicode, emojis...).

    :param text: Arbitrary string generated by Hypothesis.
    :raises AssertionError: If the corrected text differs from the input.
    """
    assert language_tool_python.utils.correct(text, []) == text


class _StubMatch:
    """Minimal stand-in for Match, classify_matches only reads .replacements."""

    def __init__(self, replacements: list[str]) -> None:
        self.replacements = replacements


@given(
    replacements_per_match=st.lists(
        st.lists(st.text(min_size=1), max_size=3),
        max_size=5,
    ),
)
@settings(max_examples=300)
def test_prop_classify_matches_invariants(
    replacements_per_match: list[list[str]],
) -> None:
    """classify_matches() follows its documented CORRECT/GARBAGE/FAULTY contract.

    An empty match list is always CORRECT; when every match has no replacements
    it is always GARBAGE; when at least one match has a non-empty replacements
    list it is always FAULTY.

    :param replacements_per_match: One replacements list per generated match.
    :raises AssertionError: If the classification does not follow the contract.
    """
    matches = [_StubMatch(replacements) for replacements in replacements_per_match]
    status = classify_matches(matches)  # type: ignore[arg-type]

    if not matches:
        assert status == TextStatus.CORRECT
    elif any(match.replacements for match in matches):
        assert status == TextStatus.FAULTY
    else:
        assert status == TextStatus.GARBAGE
